version: '3.8'

services:
  dev-db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: shivamdargan
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: nestjs-tut
    ports:
      - "5432:5432"
    networks:
      - postgres_network
networks:
  postgres_network: